### ISSUE TITLE
TagManager breaks backoffice Log Viewer styling

### ISSUE THREAD

**Issue by bowserm** [usome/UmbracoTagManager#16]
# The Problem
I'm using TagManager 1.0.4 on Umbraco 13.5.0. I noticed that when I use the built in "Log Viewer" in the Settings section of Umbraco, the svg for the search magnifying glass is huge and has `position: absolute;`.

![logviewer_broken_styles](https://github.com/user-attachments/assets/e60a3413-5881-4972-83d0-d00addf75f92)

This appears to be the result of the `/App_Plugins/TagManager/backoffice/TagManagerTree/TagManager.css` file not being specific enough with its styles.

The following CSS is from `/App_Plugins/TagManager/backoffice/TagManagerTree/TagManager.css` and is responsible for the broken styles on the Umbraco Log Viewer.

```css
.icon-search {
    position: absolute;
    color: #1b264f;
    top: 0;
    right: 0;
    margin: 20px;
    margin-bottom: 20px;
    transition: background-color 0.3s ease;
}


    .icon-search.active input {
        width: 200px;
        transition: background-color 0.3s ease;
        color: #1b264f;
    }
```

# Proposed Solution
Make sure that there is a wrapper class on all of the html used in the backoffice "Tag Manager" section of the site. Then make sure that the CSS selectors are all scoped under that class, so it can't ever affect the rest of the Umbraco backoffice. For example:

```html
<div ng-controller="TagManager.TagDisplayController" ng-class="getSelectedTagsContainerClass()" class="usome-tagmanager">
    <umb-box-header title="Tag Manager"></umb-box-header>
    ...
```

```css
.usome-tagmanager .icon-search {
    position: absolute;
    color: #1b264f;
    top: 0;
    right: 0;
    margin: 20px;
    margin-bottom: 20px;
    transition: background-color 0.3s ease;
}


    .usome-tagmanager .icon-search.active input {
        width: 200px;
        transition: background-color 0.3s ease;
        color: #1b264f;
    }
```

**Comment by BishalTimalsina12** [comment]
Hi @bowserm,

Thank you so much for bringing this issue to my attention and for offering a solution! 😊

I’ve just released [TagManager version 1.0.5](https://www.nuget.org/packages/TagManager/1.0.5) which includes your recommended CSS changes to ensure it no longer affects the log viewer in the backoffice.

Please give it a try and let me know if everything’s working smoothly for you now. I really appreciate your input—it helps make this community package better for everyone.

Best regards,
Bishal

**Comment by craigs100** [comment]
Umb V13.5.2 + TM V1.0.5
Not only did the Log Viewer have an issue but the search icon was completely missing from the main menu (as shown in your own screenshots). Applying V1.0.5 fixes the Log Viewer, and the search icon now appears in the main menu, but it's black, so you can hardly see it. So not quite fixed yet I'm afraid:-

![image](https://github.com/user-attachments/assets/1923c9d1-e829-451d-acdd-4a459c333f41)

**Comment by BishalTimalsina12** [comment]
Hi @craigs100,

Thanks for catching that! Looks like I missed a little extra CSS that slipped through. Sorry about that! I’ve just released version 1.0.6, which should fix the styling completely this time. Really appreciate your patience and feedback—it helps a ton!

Best,
Bishal
